#pragma once

#include <opencv2/opencv.hpp>
#include <opencv2/dnn.hpp>
#include <opencv2/core/cuda.hpp>
#include <opencv2/cudafilters.hpp>
#include <opencv2/cudaarithm.hpp>
#include <opencv2/cudaimgproc.hpp>
#include <opencv2/cudawarping.hpp>

#include "NvInfer.h"      // core TensorRT: builder, network, engine
#include "NvOnnxParser.h" // ONNX parser: reads your .onnx file



namespace Vision {
    class LaneNet {
    public:
        LaneNet(const char* onnxModelPath);
        LaneNet(const char* onnxModelPath, const char* enginePath);
        ~LaneNet();

        int init();
        int infer(const cv::Mat& inputFrame, cv::Mat& outputFrame);

    private:
        /**
         * @brief Converts an ONNX model to a TensorRT engine. This function will parse the ONNX model and build a TensorRT engine that can be used for inference.
         * 
         * @param onnxModelPath Path to the ONNX model file.
         * @return int 
         */
        int onnxToEngine(const char* onnxModelPath, const char* enginePath = "lanenet.engine");

        const char* m_OnnxPath   = nullptr;
        const char* m_EnginePath = nullptr;  // explicit override; if null, derived from m_OnnxPath

        // Engine object 
        nvinfer1::IRuntime* m_Runtime = nullptr;
        nvinfer1::ICudaEngine* m_Engine = nullptr;
        nvinfer1::IExecutionContext* m_Context = nullptr;

        uint32_t m_TensorWidth = 0;
        uint32_t m_TensorHeight = 0;

        static constexpr const char* INPUT_TENSOR_NAME = "image";
        static constexpr const char* OUTPUT_TENSOR_NAME = "logits";

        // ImageNet normalization constants
        static constexpr float MEAN[3] = {0.485f, 0.456f, 0.406f};
        static constexpr float STD[3]  = {0.229f, 0.224f, 0.225f};

        /**
         * @brief Input buffer for the engine. This will hold the preprocessed input image data that will be fed into the engine during inference. The buffer will be allocated based on the input tensor dimensions and data type defined in the engine.
         * 
         */
        void* m_InputBuffer = nullptr;

        /**
         * @brief Output buffer for the engine. This will hold the inference results produced by the engine after processing the input data. The buffer will be allocated based on the output tensor dimensions and data type defined in the engine. During inference, the engine will write the output data to this buffer, which can then be post-processed to extract lane markings or other relevant information.
         * 
         */
        void* m_OutputBuffer = nullptr;

        /**
         * @brief Output lane mask generated by the network. This will hold the post-processed lane mask that can be overlaid on the original frame for visualization.
         * 
         */
        cv::Mat m_LaneMaskOut;

        /**
        * @brief CUDA stream for asynchronous inference execution. This stream will be used to manage the execution of inference tasks on the GPU, allowing for non-blocking operations and improved performance by overlapping data transfers and computation.
        * 
        */
        cv::cuda::GpuMat m_D_LaneMaskOut;
    };
};

#pragma endregion